name: Python Lint and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # see > pyproject.toml > tool.poetry.dependencies
        # https://github.com/nokonoko1203/tile-operator/blob/d48a512a3693e47c7aea84d539d4634b96fc99d3/pyproject.toml#L9-L10
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Poetry Version
        run: |
          poetry --version
       - name: Poetry Install Dependencies
        run: |
          poetry install --no-interaction --dev-dependency
      - name: Format with black
        run: poetry run black --check .
      - name: isort
        run: poetry run isort .
      - name: Test with pytest
        run: |
          poetry run pytest -vv